### ISSUE TITLE
Calling C++

### ISSUE THREAD

**Issue by billtohara** [aguinet/dragonffi#18]
Somewhat inevitable, a happy internal user of dragonffi has asked about calling C++ code directly. For example, rather than wrapping member functions with a C wrapper (taking `this` explicitly) they'd like to `new` an object and invoke a member.

I imagine you have considered calling C++ code. How big a project would it be to add such support via clang/llvm. Are there showstopping gotchas due to complexity of C++? I'm just trying to understand the scope. Thanks!

**Comment by aguinet** [comment]
Hello @billtohara !

I'm first glad to know that there is at least one happy user of dragonffi :)

Supporting C++ is a complex thing due to the complexity of the C++ type system. The first goal I set to myself is having something to work for the full C type system (which is already not that easy). One "workaround" that could be easy to support is enable compilation of C++, but only allow the calling of ``extern C`` functions. Here is an exampe:

```python
CU=FFI.compile('''
template <class T>
T foo(T a) { return a+1; }

extern "c" int foo_int(int a) { return foo(a); }
''')
print(int(CU.funcs.foo_int(4))
```

I haven't implemented this yet as other things came in priority.

If you really want full C++ support, you can also try cppyy (https://cppyy.readthedocs.io/en/latest/). It uses the cling (https://github.com/root-project/cling) project (and is done by the same people)!

**Comment by billtohara** [comment]
Actually - I think for our use case we could get pretty far with the ability to call extern "C" functions from compiled C++ code. I will investigate cppyy and cling also, thank you!

The other question is about potential sources of slowness in loading headers. We have libs+headers that take 15 or 20 seconds to load although clang itself can parse and link these in less than a second. Is there perhaps a lot of work being done in the ffi as the libraries are being loaded but not yet used? E.g. a cdef of a function signature taking a struct from one of the headers can take 15 seconds to compile.

**Comment by aguinet** [comment]
Hello!

Two and a half years later, I implemented C++ compilation support, with code that can still be called through extern C functions. Check here https://github.com/aguinet/dragonffi#usage-examples for a usage example!

I also divided by ~2 the time cdef takes. It would still be a lot if it used to be 15s, but that's a start. There's still room for improvements!
