### ISSUE TITLE
[HELP][API] Passing NULL as an argument

### ISSUE THREAD

**Issue by 0xcpu** [aguinet/dragonffi#4]
Hi.

I tried generating random numbers by seeding the RNG using `srand` with return value from `time(0)`.

Here's the [script](https://gist.github.com/0xcpu/0cdf0bc7a8f155344c68013572799eea)

I would like your help in understanding why I couldn't successfully seed the RNG using `time` function. I left information about the exception and different ways of achieving my goal I've tried. If something is not clear or you need more information, please let me know.

`pydffi` was installed with `pip install pydffi`.
OS:
`Linux machine 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux`
Python version: `Python 3.6.3`

Thank you!

**Comment by aguinet** [comment]
Hello!

This script might do what you want: https://pastebin.com/CQqBcDvJ .

Some things to notice, that will be in the documentation that I have to write:

* the two headers are put in the same call to cdef. This is because, for now, types other than basic types (integers, floats, etc..) can't be used across compilation units. This is something to fix for the future.
* to create a null pointer of type `time_t`, `FFI.ptr(CU.types.time_t)` allows the creation of the type `time_t*`, and then we instantiate a new ptr (`FFI.ptr(CU.types.time_t)()`), which by default is `NULL`.

**Comment by 0xcpu** [comment]
Thank you very much for your help and explanation!
